package io.bittigerX;


import lombok.Data;

import javax.annotation.sql.DataSourceDefinition;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "USER") // in memory database H2 relational
@Data  // getter and setter auto generated by lombok
public class UserEntity {

    @Id
    @GeneratedValue
    private long id;

    private String name;

    private String username;

    /*
    MyBatis vs Hibernate: JPA ORMapping complicated, might cause lazy initialization Exception, some auto generated
    queries not quite efficient.
     */
    public UserEntity(){}

    public UserEntity(String name) {
        this.name = name;
    }
}
